all:
	gcc -o delhideMe sharedDel.c -lrt
	gcc -o sharehideMe sharedWrite.c -lrt
	gcc -o shellhideMe ogshell.c -lrt -lreadline
	gcc -o clienthideMe Client.c
	gcc -o serverhideMe Server.c -lrt
clean:
	rm delhideMe
	rm sharehideMe
	rm shellhideMe
	rm clienthideMe
	rm serverhideMe
	
